### ISSUE TITLE
Integrate upstream into SwiftGit2?

### ISSUE THREAD

**Issue by DivineDominion** [light-tech/LibGit2-On-iOS#1]
Echoing your README, replacing the build scripts would be so nice 😬  I think these alone make the package unpleasant to maintain in the long run already.

**Comment by light-tech** [comment]
Totally second replacing `SwiftGit2`'s build scripts. That also means updating the Xcode project/workspace somehow?

(Originally, we made a standalone project instead of updating SwiftGit2 scripts directly mainly to speed up development because **we developed on the minimal environment of Azure DevOps** to ensure that nobody has trouble building it and so would like to avoid as much git cloning (hence, also git sub-modules) as possible: Downloading the released source packages cut CI build time by about half. So you could imagine waiting 15 minutes for a rebuild instead of 30 minutes.)

**Comment by light-tech** [comment]
From our experience developing [MiniGit](https://github.com/light-tech/MiniGit), we have come to realize that it is probably better separating the two so we are closing the issue: In [principle](https://en.wikipedia.org/wiki/Separation_of_concerns), dependent packages (`SwiftGit2`, `MiniGit`) should not concern about how `Clibgit2` was built and should just rely on the available libgit2 APIs. Also, we use continuous integration heavily: `libgit2` should not be rebuilt every time the package updates (20 mins to rebuild). The arrangement where `MiniGit` adds `libgit2` as a prebuilt dependency works best for us.
