### ISSUE TITLE
Undefined Symbols Error

### ISSUE THREAD

**Issue by rlaurente** [light-tech/LibGit2-On-iOS#2]
Hi there, 

I able to add the method 1 and the app run smoothly, but I don't want to do non swifty codes. I tried the method 2 using package manager but I stumbled with this errors below. Do you have idea ?

I'm in xcode 13.1, swift 5.5.1

Thanks

![Screen Shot 2021-11-02 at 4 04 35 PM](https://user-images.githubusercontent.com/1804380/139944172-549fa9bf-3f85-46e8-86a6-502d8f0588a8.png)

**Comment by light-tech** [comment]
The apparent problem was the lib not being linked into the app; which was probably due to changes in Xcode 13 and Swift 5.5 on how to handle package dependencies. Unfortunately, we have not upgraded to Xcode 13 and do not plan to do so until finishing the new project MiniGit.

I would like to point out that method 2 doesn't mean you never have to write non swifty codes: We depends on SwiftGit2 to write those for us. So if there is a feature that you need but SwiftGit2 does not provide (e.g. git push, checkout, merge, ...), you must write those non swifty code yourself to implement (or find a fork that does).

That's why we are writing a new Swift package, MiniGit, in which we **write C code in C** and not Swift emulation of the C language as in SwiftGit2. It makes it easier (for us) to add new features.

**Comment by rlaurente** [comment]
Hi there,

I think you are right, I just checked right now, even the method 1 (Adding Clibgit2) doesn't also work. My goal though is just very basic clone and pull functions. Do you have further idea how to achieve linking for swift 5.5 and xcode 13 ? That might be a good start / help for me to setup basic git functions. Btw, I'm not a swift dev lol

Thanks

**Comment by light-tech** [comment]
The method that MUST work is to actually download the release file `Clibgit2.xcframework.zip`  from https://github.com/light-tech/Clibgit2/releases, extract it and add it directly to the app's [*Frameworks, Libraries, and Embedded Content* configuration in Xcode](https://developer.apple.com/documentation/swift_packages/adding_package_dependencies_to_your_app). See the first screenshot, choose **Add Files** and then look for the extracted zip instead. Swift package manager is essentially doing the same thing behind the scene.

Bear in mind that a `git pull` is the same as `git fetch + git merge`. SwiftGit2 has `fetch` but not `merge`! If you can guarantee that your pull never have conflicts (can always fast-forward), then you might get away with it via checkout (which SwiftGit2 supports).

**Comment by light-tech** [comment]
OK. Turns out the issue was due to our scripts not building the library correctly for iOS Simulator.
Took the opportunity to update libgit2 to the latest version 1.3.0 as well.
It should work now; but make sure to force a package update (right click > Update package) and a clean rebuild.

EDIT: Also note that our framework was built for x86_64 only so it only works for older **Intel-based Mac**, not the new shiny **ARM-based Apple Sillicon**.
